services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-ecommerce-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - simple-ecommerce-network

  postgres:
    image: postgres:16-alpine
    container_name: simple-ecommerce-postgres-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - simple-ecommerce-network

networks:
  simple-ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
